# Generated by Django 5.0 on 2023-12-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210322_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='task',
            name='flag',
            field=models.BooleanField(default=True),
        ),
    ]
